#!/usr/bin/env node

const db = require('../lib/loadDB')
const parser = require('../lib/arg-parser')
const jdata = require('../lib/read-json')
const args = parser.parseArgs()

function fail() { process.exit(1) }
function success() { process.exit(0) }

jdata(args.file)
.then(db.createTable)

// function main () {
//   readJson.readFileAsync(args.file) // read in the file and return the data from that file
//   .then(db.createTable)
//
// }


// TODO: Final - uncomment when main is ready to run
// main()
